### PR TITLE
fix trial not working in movie details

### LINKED ISSUE #141: Issue: Play Trailer Error/Movie Details Screen
- [ ]  On click play trailer it shows this error

Image

### PR DESCRIPTION
**Pull request by mohamedebrahem13**
image
Screenshot_20250921_133929

### CODE REVIEW

File: app/src/main/java/com/karrar/movieapp/utilities/BindingAdapter.kt [hunk 1]
```diff
@@ -260,16 +263,36 @@ fun setOverViewText(view: TextView, text: String) {
...
-        override fun onReady(youTubePlayer: YouTubePlayer) {
-            videoId?.let { youTubePlayer.cueVideo(it, 0f) }
-        }
-    })
+    if (videoId.isNullOrEmpty()) return
+
+    if (view.tag == videoId) return
+    view.tag = videoId
+
+    Log.d("YouTubeDebug", "Loading video ID: $videoId")
```
Comment (abdulazizacc) [inline app/src/main/java/com/karrar/movieapp/utilities/BindingAdapter.kt]: delete the log bro

**Review by Ahmedsayed0895 — DISMISSED** [review]

**Review by M-Abdelnabi — DISMISSED** [review]

**Review by mohamedibrahim3 — DISMISSED** [review]

**Review by abdulazizacc — APPROVED** [review]
Well done

**Review by karrar-abbas — APPROVED** [review]
